import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Clock, Sliders, CheckCircle, Calendar } from 'lucide-react';
import { getOutfits, markOutfitWorn } from '../services/outfitApi';
import MatchScore from './MatchScore';
import LoadingState from './LoadingState';
import EmptyState from './EmptyState';

export const OutfitHistory = ({ onWearAgain, onOpenStudio }) => {
  const [outfits, setOutfits] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchHistory = async () => {
    setLoading(true);
    try {
      const res = await getOutfits();
      if (res.success && Array.isArray(res.data)) {
        setOutfits(res.data);
      }
    } catch (err) {
      console.error('Fetch outfits error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHistory();
  }, []);

  const handleMarkWorn = async (id) => {
    try {
      const res = await markOutfitWorn(id);
      if (res.success) {
        setOutfits((prev) =>
          prev.map((o) => (o._id === id ? { ...o, wornCount: (o.wornCount || 1) + 1 } : o))
        );
      }
    } catch (err) {
      console.error('Mark worn error:', err);
    }
  };

  if (loading) {
    return <LoadingState message="Loading outfit history..." />;
  }

  if (outfits.length === 0) {
    return (
      <EmptyState
        title="No Saved Outfits Yet"
        description="Outfits generated by AI Stylist or saved in Outfit Studio will appear here."
        icon={Clock}
      />
    );
  }

  return (
    <div className="space-y-6 max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
      <div className="flex items-center justify-between border-b border-[#F5DABF] pb-4">
        <div>
          <span className="text-xs uppercase font-mono tracking-widest text-[#6C151E] font-bold">
            Style Log
          </span>
          <h2 className="font-serif text-3xl font-bold text-[#0A2E2C] mt-1">
            Outfit History ({outfits.length})
          </h2>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {outfits.map((outfit) => {
          const garments = outfit.garmentIds || outfit.garments || [];
          const dateStr = outfit.createdAt
            ? new Date(outfit.createdAt).toLocaleDateString('en-US', {
                month: 'short',
                day: 'numeric',
                year: 'numeric',
              })
            : 'Saved';

          return (
            <div
              key={outfit._id}
              className="bg-white border border-[#F5DABF] rounded-3xl p-5 shadow-sm hover:shadow-md transition-shadow space-y-4 flex flex-col justify-between h-full"
            >
              {/* Header Meta */}
              <div className="flex items-center justify-between text-xs font-semibold">
                <span className="font-mono text-[#0A2E2C]/70 flex items-center gap-1">
                  <Calendar className="w-3.5 h-3.5 text-[#6C151E]" /> {dateStr}
                </span>
                <span className="px-2.5 py-0.5 rounded-full text-[10px] uppercase font-bold bg-[#0F3D3A] text-[#FAF4ED]">
                  {outfit.occasion || 'Casual'}
                </span>
              </div>

              {/* Garment Thumbnail Row */}
              <div className="grid grid-cols-3 gap-2">
                {garments.slice(0, 3).map((g, idx) => (
                  <div
                    key={g._id || idx}
                    className="aspect-3/4 rounded-xl overflow-hidden bg-[#FAF4ED] border border-[#F5DABF]"
                  >
                    <img
                      src={g.imageUrl || g.image}
                      alt={g.title}
                      className="w-full h-full object-cover"
                    />
                  </div>
                ))}
              </div>

              {/* Score Bar */}
              <MatchScore score={outfit.score || 85} label="Compatibility Score" />

              {/* Actions */}
              <div className="grid grid-cols-2 gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => {
                    if (onWearAgain) onWearAgain(garments);
                    else if (onOpenStudio) onOpenStudio(garments);
                  }}
                  className="py-2.5 px-3 bg-[#0F3D3A] hover:bg-[#0A2E2C] text-[#FAF4ED] text-xs font-bold uppercase tracking-wider rounded-xl transition-all flex items-center justify-center gap-1.5 shadow-xs cursor-pointer"
                >
                  <Sliders className="w-3.5 h-3.5 text-[#F5DABF]" />
                  Wear Again
                </button>

                <button
                  type="button"
                  onClick={() => handleMarkWorn(outfit._id)}
                  className="py-2.5 px-3 bg-[#FAF4ED] border border-[#F5DABF] hover:bg-[#F5DABF]/50 text-[#0A2E2C] text-xs font-bold uppercase tracking-wider rounded-xl transition-all flex items-center justify-center gap-1.5 cursor-pointer"
                >
                  <CheckCircle className="w-3.5 h-3.5 text-[#0F3D3A]" />
                  Mark Worn ({outfit.wornCount || 1})
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default OutfitHistory;
